# Generated by Django 5.0.7 on 2024-08-16 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='registration_deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
