# Generated by Django 5.0.7 on 2024-08-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_alter_workshop_registration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
