# Generated by Django 5.0.7 on 2024-09-12 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_workshop_workshop_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='host',
            new_name='tutor',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='workshop_admin',
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='workshop.workshop')),
            ],
        ),
    ]
