# Generated by Django 5.0.7 on 2024-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='host',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
