# Generated by Django 5.0.7 on 2024-08-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
