# Generated by Django 5.0.7 on 2024-08-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_workshop_registration_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='prerequisite',
        ),
        migrations.AddField(
            model_name='workshop',
            name='prerequisite',
            field=models.TextField(blank=True),
        ),
    ]
